CREATE TABLE users(
  user_id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,  
  role NUMERIC(1) NOT NULL DEFAULT 0,
  cart_id NUMERIC(10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
);